# Generated by Django 4.2.4 on 2023-08-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=100)),
                ('register_date', models.DateField(auto_now_add=True, null=True)),
                ('pet_name', models.TextField(null=True)),
                ('pet_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('pet_image', models.TextField(null=True)),
                ('pet_breed', models.TextField(null=True)),
                ('pet_lost', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
            ],
            options={
                'db_table': 'PET_INFO',
            },
        ),
        migrations.CreateModel(
            name='Report_info',
            fields=[
                ('report_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('pet_image', models.TextField()),
                ('location', models.TextField()),
                ('lat_lon', models.TextField()),
                ('etc', models.TextField()),
            ],
            options={
                'db_table': 'REPORT_INFO',
            },
        ),
    ]
