# Generated by Django 4.2.4 on 2023-08-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_info',
            name='pet_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='pet_image',
            field=models.ImageField(null=True, upload_to='pet_images/'),
        ),
    ]
