# Generated by Django 4.2.4 on 2023-08-07 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pet', '0003_pet_info_pet_date_alter_pet_info_pet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='register_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
