# Generated by Django 4.2.4 on 2023-08-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0005_alter_pet_info_pet_lost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_info',
            name='pet_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1),
        ),
    ]
