# Generated by Django 4.2.4 on 2023-08-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_schedule_image_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='diary_date',
            field=models.TextField(null=True),
        ),
    ]
